services:
  app:
    build: .
    container_name: gold-project
    ports:
      - "4000:4000"
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - FRONTEND_PORT=3000
      - BACKEND_PORT=4000
      - PORT=4000
      - MONGODB_URL=mongodb://mongo:27017/gold-project-db
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6
    container_name: gold-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=gold-project-db
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
